void loadFromFile(int *size);
void saveToFile(int *size);
int checkAddUser(char *check, int *size, int flag);
void addUser(int *size);void displayUserDetail(int *size);
void lockUnlockAccounts(int *size);
void deleteAccounts(int *size);
void menuAdmin(int *size);
void menuUser(int size, int myIndex);
void signInAdmin(char *email, char *pass, int *size);
void signInUser(char *email, char *pass, int *size);
void searchByName(int *size);
void arrangeAccounts(int size);
void searchByID(int *size);
void depositMoney(int myIndex);
void withdrawMoney(int myIndex, int *amount);
void checkWithdrawMoney(int myIndex);
void transferMoney(int *size, int myIndex);
void checkTransferMoney(int *size, int myIndex, int indexTransfer);
void IDeditAccounts(int *size);
void editAccounts(int *size, int index);
void editPass(int myIndex);
void backOrExit();
int checkFullName(char fullName[], int length);
int checkBirthday(int day, int month, int year);
